### ISSUE TITLE
Batch verification of multiple artifacts

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-verifier#191] opened 2022-08-05 01:04 UTC
Currently `slsa-verifier` needs to be run once per artifact listed in a provenance statement. We could provide a way to specify multiple artifacts at once so they can all be verified in one go.

**Comment by ianlewis** [comment] 2022-08-05 01:06
I'm not sure if this is particularly high priority since
1. Provenance is somewhat likely to be created 1:1 with artifacts.
2. I think users will always be verifying a subset of the artifacts listed in provenance.
3. Feedback to the user becomes more complicated. Which artifact was the one that failed? Is a simple human readable error message sufficient?

**Comment by laurentsimon** [comment] 2022-08-05 21:33
duplicate of https://github.com/slsa-framework/slsa-verifier/issues/91. I'll close this issue and copy over your comment.

**Closed** 2022-08-05 21:33 UTC
Labels: duplicate
